---
apiVersion: v1
kind: Service
metadata:
  name: quang-test-mariadb-galera-headless
  namespace: "default"
  labels:
    app.kubernetes.io/instance: quang-test
    app.kubernetes.io/name: mariadb-galera
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: galera
      port: 4567
      targetPort: galera
      appProtocol: mysql
    - name: ist
      port: 4568
      targetPort: ist
      appProtocol: mysql
    - name: sst
      port: 4444
      targetPort: sst
      appProtocol: mysql
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: quang-test
    app.kubernetes.io/name: mariadb-galera
