---
apiVersion: v1
kind: Secret
metadata:
  name: quang-test-mariadb-galera
  namespace: "default"
  labels:
    app.kubernetes.io/instance: quang-test
    app.kubernetes.io/name: mariadb-galera
type: Opaque
data:
  mariadb-root-password: "NGp3dnUyVnBZTQ=="
  mariadb-password: "cG1KV1NRdklzNQ=="
  mariadb-galera-mariabackup-password: "eGFKaGNlbUJVbA=="
