---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quang-test-mariadb-galera
  namespace: "default"
  labels:
    app.kubernetes.io/instance: quang-test
    app.kubernetes.io/name: mariadb-galera
automountServiceAccountToken: false
