---
# Source: mariadb-galera/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: quang-test-mariadb-galera
  namespace: "default"
  labels:
    app.kubernetes.io/instance: quang-test
    app.kubernetes.io/name: mariadb-galera
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      appProtocol: mysql
  selector:
    app.kubernetes.io/instance: quang-test
    app.kubernetes.io/name: mariadb-galera
